### ISSUE TITLE
Unable to start VM with kubevirt

### ISSUE THREAD

**Issue by chinadd** [kubevirt/kubevirt#2766]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
unable to start the VM 
```
[centos@kubevirt-test-2 yaml]$ ./virtctl start virtualmachineinstance.kubevirt.io/vmi-centos7
Error starting VirtualMachine the server has asked for the client to provide credentials
[centos@kubevirt-test-2 yaml]$ sudo ./virtctl start virtualmachineinstance.kubevirt.io/vmi-centos7
Error starting VirtualMachine Put http://localhost:8080/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachines/virtualmachineinstance.kubevirt.io/vmi-centos7/start: dial tcp [::1]:8080: connect: connection refused
```

**What you expected to happen**:
Should be able to start the VM 

**How to reproduce it (as minimally and precisely as possible)**:
1. Have kubevirt installed (https://github.com/kubevirt/demo). 
2. Deploy the pv and pvc by `kubectl apply -f https://github.com/dlambrig/kubevirt-lustre/blob/master/yaml/pv-mds.yaml` and `kubectl -f apply -f https://github.com/dlambrig/kubevirt-lustre/blob/master/yaml/pvc-mds.yaml`. Change the metadata name field in pvc to mydisk to be consistent. Also, adjust the storage size to fit into your hardware configuration. 
3. Deploy the VM by`kubectl apply -f https://github.com/dlambrig/kubevirt-lustre/blob/master/yaml/centos7.yaml`. 

**Anything else we need to know?**:
vm instance created succesfully
```
[centos@kubevirt-test-2 yaml]$ kubectl describe virtualmachineinstance.kubevirt.io/vmi-centos7
Name:         vmi-centos7
Namespace:    default
Labels:       special=key
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachineInstance","metadata":{"annotations":{},"labels":{"special":"key"},"name":"vmi-c...
              kubevirt.io/latest-observed-api-version: v1alpha3
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2019-10-01T00:38:14Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:        5
  Resource Version:  706000
  Self Link:         /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/vmi-centos7
  UID:               85a825da-51a9-46b5-99bd-26d41e67481a
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   mydisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
      Rng:
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  13bc1897-7b50-4661-872a-f2faf78d72e0
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  1024M
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  0
  Volumes:
    Name:  mydisk
    Persistent Volume Claim:
      Claim Name:  mydisk
    Container Disk:
      Image:              dlambrig/centos7:latest
      Image Pull Policy:  Always
    Name:                 containerdisk
    Cloud Init No Cloud:
      User Data:  #cloud-config
password: centos
chpasswd: { expire: False }
    Name:  cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2019-10-01T00:38:15Z
    Message:               0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm.
    Reason:                Unschedulable
    Status:                False
    Type:                  PodScheduled
  Phase:                   Scheduling
  Qos Class:               Burstable
Events:
  Type    Reason            Age    From                       Message
  ----    ------            ----   ----                       -------
  Normal  SuccessfulCreate  5m58s  virtualmachine-controller  Created virtual machine pod 
```
output when describing the vm pod
```
[centos@kubevirt-test-2 ~]$ kubectl get po -n default
NAME                              READY   STATUS    RESTARTS   AGE
virt-launcher-vmi-centos7-4jm66   0/2     Pending   0          14h
[centos@kubevirt-test-2 ~]$ kubectl describe po virt-launcher-vmi-centos7-4jm66 
Name:           virt-launcher-vmi-centos7-4jm66
Namespace:      default
Priority:       0
Node:           <none>
Labels:         kubevirt.io=virt-launcher
                kubevirt.io/created-by=85a825da-51a9-46b5-99bd-26d41e67481a
                special=key
Annotations:    kubevirt.io/domain: vmi-centos7
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  VirtualMachineInstance/vmi-centos7
Containers:
  volumecontainerdisk:
    Image:      dlambrig/centos7:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/container-disk
    Args:
      --copy-path
      /var/run/kubevirt-ephemeral-disks/container-disk-data/85a825da-51a9-46b5-99bd-26d41e67481a/disk_1
    Limits:
      cpu:     100m
      memory:  20M
    Requests:
      cpu:        10m
      memory:     1M
    Readiness:    exec [/usr/bin/container-disk --health-check] delay=1s timeout=1s period=1s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /usr/bin from virt-bin-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks/container-disk-data/85a825da-51a9-46b5-99bd-26d41e67481a from container-disks (rw)
  compute:
    Image:      index.docker.io/kubevirt/virt-launcher@sha256:17c6d0bbedf9e24085011c96e002569444133b331f124d0177a77d45cb3ac5e4
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/virt-launcher
      --qemu-timeout
      5m
      --name
      vmi-centos7
      --uid
      85a825da-51a9-46b5-99bd-26d41e67481a
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --container-disk-dir
      /var/run/kubevirt/container-disks
      --readiness-file
      /var/run/kubevirt-infra/healthy
      --grace-period-seconds
      15
      --hook-sidecars
      0
      --less-pvc-space-toleration
      10
    Limits:
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
    Requests:
      cpu:                            100m
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
      memory:                         1187554432
    Readiness:                        exec [cat /var/run/kubevirt-infra/healthy] delay=4s timeout=5s period=1s #success=1 #failure=5
    Environment:                      <none>
    Mounts:
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-infra from infra-ready-mount (rw)
      /var/run/kubevirt-private/vmi-disks/mydisk from mydisk (rw)
      /var/run/kubevirt/container-disks from container-disks (rw)
      /var/run/libvirt from libvirt-runtime (rw)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  mydisk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mydisk
    ReadOnly:   false
  infra-ready-mount:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:  
  virt-bin-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt/init/usr/bin
    HostPathType:  
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  container-disks:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt/container-disks/85a825da-51a9-46b5-99bd-26d41e67481a
    HostPathType:  
QoS Class:         Burstable
Node-Selectors:    kubevirt.io/schedulable=true
Tolerations:       node.kubernetes.io/not-ready:NoExecute for 300s
                   node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm.
```
starting testvm is successful
```
[centos@kubevirt-test-2 ~]$ kubectl apply -f https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml
virtualmachine.kubevirt.io/testvm created
[centos@kubevirt-test-2 ~]$ kubectl describe vm testvm
Name:         testvm
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachine","metadata":{"annotations":{},"name":"testvm","namespace":"default"},"spec":{"...
              kubevirt.io/latest-observed-api-version: v1alpha3
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachine
Metadata:
  Creation Timestamp:  2019-10-02T23:02:54Z
  Generation:          2
  Resource Version:    1070036
  Self Link:           /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachines/testvm
  UID:                 8da76d2e-8101-4b97-b7e7-4b3e8fcb9b58
Spec:
  Running:  false
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        kubevirt.io/domain:  testvm
        kubevirt.io/size:    small
    Spec:
      Domain:
        Devices:
          Disks:
            Disk:
              Bus:  virtio
            Name:   rootfs
            Disk:
              Bus:  virtio
            Name:   cloudinit
          Interfaces:
            Bridge:
            Name:  default
        Machine:
          Type:  
        Resources:
          Requests:
            Memory:  64M
      Networks:
        Name:  default
        Pod:
      Volumes:
        Container Disk:
          Image:  kubevirt/cirros-registry-disk-demo
        Name:     rootfs
        Cloud Init No Cloud:
          userDataBase64:  SGkuXG4=
        Name:              cloudinit
Status:
Events:  <none>
[centos@kubevirt-test-2 ~]$ kubectl virt start testvm
VM testvm was scheduled to start
[centos@kubevirt-test-2 ~]$ kubectl describe vmi testvm
Name:         testvm
Namespace:    default
Labels:       kubevirt.io/domain=testvm
              kubevirt.io/size=small
Annotations:  kubevirt.io/latest-observed-api-version: v1alpha3
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2019-10-02T23:03:14Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generate Name:  testvm
  Generation:     4
  Owner References:
    API Version:           kubevirt.io/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  testvm
    UID:                   8da76d2e-8101-4b97-b7e7-4b3e8fcb9b58
  Resource Version:        1070092
  Self Link:               /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvm
  UID:                     1dae84a3-c80a-4ad2-9700-9f2839c833eb
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   rootfs
        Disk:
          Bus:  virtio
        Name:   cloudinit
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  5a9fc181-957e-5c32-9e5a-2de5e9673531
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  64M
  Networks:
    Name:  default
    Pod:
  Volumes:
    Container Disk:
      Image:              kubevirt/cirros-registry-disk-demo
      Image Pull Policy:  Always
    Name:                 rootfs
    Cloud Init No Cloud:
      userDataBase64:  SGkuXG4=
    Name:              cloudinit
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2019-10-02T23:03:14Z
    Message:               0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm.
    Reason:                Unschedulable
    Status:                False
    Type:                  PodScheduled
  Phase:                   Scheduling
  Qos Class:               Burstable
Events:
  Type    Reason            Age   From                       Message
  ----    ------            ----  ----                       -------
  Normal  SuccessfulCreate  7s    virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-2vf5g
```
**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.19.0", GitCommit:"b54712d720ae7bde6400cd3bb81087f2694b2a40", GitTreeState:"clean", BuildDate:"2019-07-04T07:08:33Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: 
https://github.com/dlambrig/kubevirt-lustre/blob/master/yaml/centos7.yaml
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux 3.10.0-862.14.4.el7.x86_64
- Install tools:kubevirt
- Others:minikube version: v1.4.0, QEMU emulator version 1.5.3 (qemu-kvm-1.5.3-167.el7_7.1), Copyright (c) 2003-2008 Fabrice Bellard

**Comment by cynepco3hahue** [comment]
@chinadd Do your hosts support nested virtualization? See - https://kubevirt.io/user-guide/docs/latest/administration/intro.html

**Comment by rmohr** [comment]
Interesting, I think that there are two issues. First that the node probably does not have /dev/kvm, but kubevirt is not configured to use software emulation.

Second, it looks like `virtctl` can't authenticate, but `kubectl` can. That can have two reasons: First, some exotic auth plugin is used and we don't support that correctly, second something new got introduced in kubernetes 1.16, and we need to rebuild `virtctl` with the latest kubernetes sdk.

**Comment by rmohr** [comment]
@chinadd how did you create the cluster?

**Comment by rmohr** [comment]
Found two changes regarding to auth, may or may not be related: https://kubernetes.io/docs/setup/release/notes/#auth

**Comment by chinadd** [comment]
> @chinadd Do your hosts support nested virtualization? See - https://kubevirt.io/user-guide/docs/latest/administration/intro.html

I am not sure about this. Below is the output for virtualization support.
```
[centos@kubevirt-test-2 ~]$ virt-host-validate qemu
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller mount-point                  : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpu' controller mount-point                     : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuacct' controller mount-point                 : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'cpuset' controller mount-point                  : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'devices' controller mount-point                 : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for cgroup 'blkio' controller mount-point                   : PASS
  QEMU: Checking for device assignment IOMMU support                         : WARN (No ACPI DMAR table found, IOMMU either disabled in BIOS or not supported by this hardware platform)
```

**Comment by chinadd** [comment]
> @chinadd how did you create the cluster?

I created the minikube cluster like this
```
$ minikube config set vm-driver kvm2
$ minikube start --memory 4096
```

**Comment by chinadd** [comment]
> Interesting, I think that there are two issues. First that the node probably does not have /dev/kvm, but kubevirt is not configured to use software emulation.

I think so. 
```
[centos@kubevirt-test-2 ~]$ minikube ssh -- test -e /dev/kvm
ssh: Process exited with status 1
[centos@kubevirt-test-2 ~]$ minikube ssh -- ls -al /dev/kvm
ls: cannot access '/dev/kvm': No such file or directory
ssh: Process exited with status 2
```

**Comment by chinadd** [comment]
> Second, it looks like `virtctl` can't authenticate, but `kubectl` can. That can have two reasons: First, some exotic auth plugin is used and we don't support that correctly, second something new got introduced in kubernetes 1.16, and we need to rebuild `virtctl` with the latest kubernetes sdk.

The newest version of `virtctl` is v0.21.0, I will try by reinstallation of this version

**Comment by chinadd** [comment]
> @chinadd Do your hosts support nested virtualization? See - https://kubevirt.io/user-guide/docs/latest/administration/intro.html

May I ask what makes you ask this?

**Comment by slintes** [comment]
> > @chinadd Do your hosts support nested virtualization? See - https://kubevirt.io/user-guide/docs/latest/administration/intro.html
> 
> May I ask what makes you ask this?

The kubernetes node is running in a VM (because of the minikube KVM driver), and you want to start another VM inside that VM. So you need either nested virt, or you need to enable software emulation. See [0] for how to enable nested virt on CentOS 7. Once you set it up, `$ minikube ssh -- test -e /dev/kvm` won't return an error anymore.

Will try to reproduce the auth issue now.

[0] https://www.linuxtechi.com/enable-nested-virtualization-kvm-centos-7-rhel-7/

**Comment by slintes** [comment]
hm, I can't reproduce the auth problem, neither with downloaded virtctl nor with krew... :thinking: 
```
$ k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compi
ler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compi
ler:"gc", Platform:"linux/amd64"}
$ k get node
NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   28m   v1.16.0

# virtctl directly
$ ./virtctl version
Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
ux/amd64"}
Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
ux/amd64"}
$ ./virtctl start vm-cirros
VM vm-cirros was scheduled to start

# via krew
$ k virt version
Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
ux/amd64"}
Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
ux/amd64"}
$ k virt stop vm-cirros
VM vm-cirros was scheduled to stop
```

**Comment by chinadd** [comment]
> hm, I can't reproduce the auth problem, neither with downloaded virtctl nor with krew... 🤔
> 
> ```
> $ k version
> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compi
> ler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compi
> ler:"gc", Platform:"linux/amd64"}
> $ k get node
> NAME       STATUS   ROLES    AGE   VERSION
> minikube   Ready    master   28m   v1.16.0
> 
> # virtctl directly
> $ ./virtctl version
> Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
> ux/amd64"}
> Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
> ux/amd64"}
> $ ./virtctl start vm-cirros
> VM vm-cirros was scheduled to start
> 
> # via krew
> $ k virt version
> Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
> ux/amd64"}
> Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"lin
> ux/amd64"}
> $ k virt stop vm-cirros
> VM vm-cirros was scheduled to stop
> ```

Thanks for the effort! This error message is specific to the yaml file (https://github.com/dlambrig/kubevirt-lustre/blob/master/yaml/centos7.yaml) I am using. I didn't see the error either when trying to start testvm (https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml)

**Comment by slintes** [comment]
Oh... now I see it :)
It doesn't have anything to do with your VM, but how you use virtctl:
1. virtctl just takes the name of the virtualmachine as argument, without resource type, no need for `virtualmachineinstance.kubevirt.io/`
2. `virtualmachine*instances*` can't be started at all, they are running per definition. You can start/stop `virtualmachines`, which will create/delete the `virtualmachine*instance*` for you.

(It's still interesting why we get this misleading error message though, which I can reproduce)

**Comment by chinadd** [comment]
> Oh... now I see it :)
> It doesn't have anything to do with your VM, but how you use virtctl:
> 
> 1. virtctl just takes the name of the virtualmachine as argument, without resource type, no need for `virtualmachineinstance.kubevirt.io/`
> 2. `virtualmachine*instances*` can't be star 
 ted at all, they are running per definition. You can start/stop `virtualmachines`, which will create/delete the `virtualmachine*instance*` for you.
> 
> (It's still interesting why we get this misleading error message though, which I can reproduce)

I see. Thanks!

**Comment by chinadd** [comment]
> Oh... now I see it :)
> It doesn't have anything to do with your VM, but how you use virtctl:
> 
> 1. virtctl just takes the name of the virtualmachine as argument, without resource type, no need for `virtualmachineinstance.kubevirt.io/`
> 2. `virtualmachine*instances*` can't be started at all, they are running per definition. You can start/stop `virtualmachines`, which will create/delete the `virtualmachine*instance*` for you.
> 
> (It's still interesting why we get this misleading error message though, which I can reproduce)

I got some new situations when running the new commands
```
Error starting VirtualMachine Put https://192.168.39.94:8443/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachines/vmi-centos7/start: read tcp 192.168.39.1:56460->192.168.39.94:8443: read: connection timed out
```
And I checked the disk space usage before and after I start the VM
before:
```
[centos@kubevirt-test yaml]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        10G  8.0G  2.1G  80% /
devtmpfs        3.8G     0  3.8G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G   17M  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           783M     0  783M   0% /run/user/1000
```
after
```
[centos@kubevirt-test yaml]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        10G   10G  208K 100% /
devtmpfs        3.8G     0  3.8G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G   17M  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           783M     0  783M   0% /run/user/1000
tmpfs           783M     0  783M   0% /run/user/0
```
Probably due to the almost full disk space, minikube is paused
```
[centos@kubevirt-test ~]$ minikube status
host: Paused
kubelet: 
apiserver: 
kubectl: 
```
and I can't describe the VM or delete the deployment either
```
[centos@kubevirt-test yaml]$ kubectl describe virtualmachineinstance.kubevirt.io/vmi-centos7
Unable to connect to the server: dial tcp 192.168.39.94:8443: connect: no route to host
[centos@kubevirt-test yaml]$ kubectl delete -f centos7.yaml 
error: error when deleting "centos7.yaml": Delete https://192.168.39.94:8443/apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/vmi-centos7: dial tcp 192.168.39.94:8443: connect: no route to host
```

**Comment by slintes** [comment]
Seems you are still trying to start a virtualmachine**instance**. That is not possible. VMIs are always running. You can only start virtualmachines.
Also, your centos7 VM seems to be so big that your very small machine (only 2 GB space left before creating the VMI) is running out of space and just stops working.

**Comment by chinadd** [comment]
> Seems you are still trying to start a virtualmachine**instance**. That is not possible. VMIs are always running. You can only start virtualmachines.
> Also, your centos7 VM seems to be so big that your very small machine (only 2 GB space left before creating the VMI) is running out of space and just stops working.

So I deployed the YAML file for VM and ran `kubectl virt start <name of VM> `. That seems to be the same as the way I start the testVM. Also, I am kind of lost about `VM` vs `VM instance` since instance and VM are sometimes interchangeable on cloud platforms like GCP.  
Disk usage is another issue. I need to try with a larger instance but I am not sure that will work since the disk space keeps growing ever since I started the minikube even when I delete deployment (https://github.com/chinadd/log/blob/master/chart.png).

**Comment by slintes** [comment]
> disk space keeps growing

yes, because downloaded docker images aren't removed automatically

Looking for a good explanation of VM vs VMI...

**Comment by chinadd** [comment]
> > disk space keeps growing
> 
> yes, because downloaded docker images aren't removed automatically
> 
> Looking for a good explanation of VM vs VMI...

OK we got it working by removing the PersistentVolumeClaim part of VM. 
```
[centos@kubernetes-master kubevirt-lustre]$ kubectl get vmi
NAME          AGE   PHASE     IP            NODENAME
vmi-centos7   16m   Running   172.17.0.11   minikube
```

**Comment by phoerious** [comment]
I am still getting this authentication error with 0.24.0:

```
Error starting VirtualMachine the server has asked for the client to provide credentials
```

kubectl works just fine, but virtctl cannot connect. Any solutions for this? kubectl is installed via Snap, but the config is in ~/.kube/config and accessible to virtctl.

**Comment by talcoh2x** [comment]
i have the same issue 
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: testvm
spec:
  #terminationGracePeriodSeconds: 30
  # pass: gocubsgo
  # user: cirros
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/cirros-registry-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=




kubectl virt start testvm -v 10
Error starting VirtualMachine the server has asked for the client to provide credentials

someone can help ?

**Comment by mlushpenko** [comment]
I know this is an old issue, but I run into the same problem because GKE uses auth plugin to authenticate. I created a service account with access token and then run the command like this: `virtctl --token="$TOKEN" start testvm` and then it worked.

I haven't googled too much yet, maybe there is some way to make it work with auth plugin, but at least there is a solution if you stumble upon this, docs haven't been the best so far.
